---
title: "Heart Disease Prediction model"
output: html_document
author: Sumiti Sandhu
---

```{r reading data in R}
h<- read.csv("heart.csv", header=T)
```


```{r checking collinearity between the features, multivariate analysis}
library(corrplot)
corMatMy <- cor(h)
corrplot(corMatMy, order = "hclust", tl.cex = 0.7)
```


```{r creating a new variable to store target information}
h$disease <- as.factor(h$target)
```


```{r converting integer to character for better plots}
library(base)
h$target <- gsub(0,"Disease",h$target)
h$target <- gsub(1,"No disease",h$target)
```


```{r Data exploration, univariate analysis for numerical/continuous features}
library(ggplot2)
library(reshape2)
```


```{r creating df of numerical variables}
nf<- h[,c("age","trestbps","chol","thalach","oldpeak","target")]
```


```{r Plot histograms of variables group by target}
ggplot(data = melt(nf, id.var = "target"), mapping = aes(x = value)) + 
  geom_histogram(bins = 10, aes(fill=target), alpha=0.5) + 
  facet_wrap(~variable, scales = 'free_x') +
  ggtitle("Numerical features")
```


```{r creating df of continuos variables}
cf<- h[,c("sex","cp","fbs","restecg","exang","slope","thal","target")]
```


```{r Plot barplots of variables group by target}
ggplot(data = melt(cf, id.var = "target"), mapping = aes(x = value)) + 
  geom_bar(aes(fill=target), alpha=0.5) + 
  facet_wrap(~variable, scales =      'free_x')+
  ggtitle("Categorical features")
```


```{r splitting the dataset into training and testing dataset randomly by a 75/25 proportion}
smp_size_raw <- floor(0.75 * nrow(h))
train_ind_raw <- sample(nrow(h), size = smp_size_raw)
train_raw.df <- as.data.frame(h[train_ind_raw, ])
test_raw.df <- as.data.frame(h[-train_ind_raw, ])

```


```{r logistic regression(LR) and results}
fit<- glm(disease~.-target, family= binomial, data = train_raw.df)
summary(fit)

library(boot)
glm.diag.plots(fit)
```


```{r Calculating R-Squared}
library(rsq)
rsq(fit)
rsq(fit,adj = T)
```


```{r performing step wise selection using AIC}
library(MASS)
stepAIC(fit,direction = "both")
```


```{r second LR model without insignificant features}
fit2<- glm(disease ~ sex + cp + trestbps + chol + restecg + 
             thalach + exang + oldpeak + slope + ca + thal-target, family = binomial, 
           data = train_raw.df)

summary(fit2)

glm.diag.plots(fit2)
rsq(fit2)
rsq(fit2,adj = T)
```


```{r compare the two logistic regression models}
anova(fit2,fit)
```


```{r make predictics}
predictTrain=predict(fit2,type="response")
```


```{r Plotting ROCR curve}
library(ROCR)
ROCRpred_fit2=prediction(predictTrain, train_raw.df$disease)
ROCRperf_fit2=performance(ROCRpred_fit2,'tpr','fpr')
auc.train_fit2 <- performance(ROCRpred_fit2, measure = "auc")
auc.train_fit2 <- auc.train_fit2@y.values

plot(ROCRperf_fit2)
plot(ROCRperf_fit2,colorize=TRUE,print.cutoffs.at=seq(0,1,by=0.1),
     text.adj=c(-0.2,1.7))
abline(a=0, b= 1)
text(x = .25, y = .65 ,paste("AUC = ", round(auc.train_fit2[[1]],3), sep = ""))

legend('bottomright', 
       c( "Logistic Regression" ),
       col=1,lty=1, cex=0.5, lwd=1.5,bty='n') 
```


```{r odds ratios and 95% CI}
cbind(coef(fit2), confint(fit2))
```


```{r Linear Discriminant Analysis}
library(MASS)
h.lda <- lda(disease~.-target, data = train_raw.df)

h.lda.predict <- predict(h.lda, newdata = test_raw.df)

h.lda.predict$class
```


```{r ROC AUC PLOT}
h.lda.predict.posteriors <- as.data.frame(h.lda.predict$posterior)

# Evaluate the model
#library(ROCR)
ROCRpred_lda <- prediction(h.lda.predict.posteriors[,2], test_raw.df$target)
ROCRperf_lda = performance(ROCRpred_lda, measure = "tpr", x.measure = "fpr")
auc.train_lda <- performance(ROCRpred_lda, measure = "auc")
auc.train_lda <- auc.train_lda@y.values
```


```{r Plot for LDA model}
plot(ROCRperf_lda,colorize=TRUE,print.cutoffs.at=seq(0,1,by=0.1),
     text.adj=c(-0.2,1.7))
abline(a=0, b= 1)
text(x = .25, y = .65 ,paste("AUC = ", round(auc.train_lda[[1]],3), sep = ""))

legend('bottomright', 
       c( "LDA on Raw data" ),
       col=1,lty=1, cex=0.5, lwd=1.5,bty='n') 
```


```{r Principal Component Analysis}
h$disease <- as.numeric(h$disease)
h_pca<- subset(h,select=-c(14))

h.pr <- prcomp(h_pca, center = TRUE, scale = TRUE)
summary(h.pr)
```


```{r PC1 vs PC2 plot}
library("factoextra")
fviz_pca_ind(h.pr, geom.ind = "point", pointshape = 21, 
             pointsize = 2, 
             fill.ind = as.factor(h$target), 
             col.ind = "blue", 
             palette = "jco", 
             addEllipses = TRUE,
             label = "var",
             col.var = "black",
             repel = TRUE,
             legend.title = "Target") +
  ggtitle("2D PCA-plot") +
  theme(plot.title = element_text(hjust = 0.5))
```


```{r creating a new df with 6 Principal Components and target variable }
h.pcst <- h.pr$x[,1:6]
h.pcst <- cbind(h.pcst,h$disease)
colnames(h.pcst)[7] <- "target"

smp_size_pca <- floor(0.75 * nrow(h.pcst))
train_ind_pca <- sample(nrow(h.pcst), size = smp_size_pca)

train.df <- as.data.frame(h.pcst[train_ind_pca, ])
test.df <- as.data.frame(h.pcst[-train_ind_pca, ])

h.lda_pca <- lda(target ~ PC1 + PC2 + PC3 + PC4 + PC5 + PC6, data = train.df)
h.lda_pca.predict <- predict(h.lda_pca, newdata = test.df)
```


```{r ROC AUC PLOT, Posteriors as a dataframe.}
h.lda_pca.predict.posteriors <- as.data.frame(h.lda_pca.predict$posterior)

#Evaluate the model
library(ROCR)
ROCRpred_pca <- prediction(h.lda_pca.predict.posteriors[,2], test.df$target)
ROCRperf_pca = performance(ROCRpred_pca, measure = "tpr", x.measure = "fpr")
auc.train_pca <- performance(ROCRpred_pca, measure = "auc")
auc.train_pca <- auc.train_pca@y.values
```


```{r Plot ROC AUC plot}
plot(ROCRperf_pca, colorize=TRUE,print.cutoffs.at=seq(0,1,by=0.2),
     text.adj=c(-0.2,1.7))
abline(a=0, b= 1)
text(x = .25, y = .65 ,paste("AUC = ", round(auc.train_pca[[1]],3), sep = ""))
legend('bottomright', 
       c("LDA on PCA data"),
       col=1,lty=1, cex=0.5, lwd=1.5,bty='n') 
```

